
<div class="sixteen columns">
	<img src="/images/thankyou.png" width="960">
</div>
<div class="offset-by-eleven">
	<a href="http://www.flickr.com/photos/wwworks/4759535950/">Original Image By Woodleywonderworks</a>
</div>
<div class="one-third column">
	<h3>Thanks</h3>
	<p>Thanks for downloading the speedy skeleton.</p>
</div>
<div class="one-third column">
	<h3>Add you Own Content</h3>
	<p>At some point you'll want to replace this with your home page.  Do it whenever you feel like (sooner would be better).</p>
</div>
<div class="one-third column">
	<h3>Help</h3>
	<p>If you want some more help checkout these resources.</p>
	<ul>
		<li><a href="http://www.thisprogrammingthing.com/category/speedy/">Blog</a></li>
	</ul>
</div>

<div class="sixteen columns">
	You're working on: Speedy_Featuretoggle.
	
	
</div>
