<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="chrome=1">
		<title>Page Title Goes Here</title>
		<?php echo $this->CSS()->getLink('default'), $this->CSS()->getLink($this->module);?>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link rel="shortcut icon" href="/images/favicon.ico">
		<link rel="apple-touch-icon" href="/images/apple-touch-icon.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
	</head>
	<body>
		<noscript id="noscript">
			<div class="container">
				<div class="sixteen columns">
					This site works best with JavaScript enabled and if you're getting this message it isn't turned on.  
					<a href="">[More Info]</a>
				</div>
			</div>
		</noscript>