<div id="header">
	<div class="container">
		<div class="thirteen columns">
			<ul id="siteLinks">
				<li><a href="<?php echo $this->url(array('module'=>'help', 'controller'=>'index', 'action'=>'index'),'default',true);?>">Help</a></li>
				<li><a href="<?php echo $this->url(array('module'=>'help', 'controller'=>'helprequest', 'action'=>'index'),'default',true);?>">Problems With This Page?</a></li>
			</ul>
		</div>
		<div class="three columns">
			<div id="userInformation">
				<img src="">
				<a href="">UserName</a> 
			</div>
		</div>
		
		<div class="four columns">
			<h1><a href="/">Site</a></h1> 
		</div>
		<div class="twelve columns">
			Page Nav goes here
		</div>
	</div>
</div>