<?php echo $this->partial('head.phtml');?>
<?php echo $this->partial('header.phtml');?>
<br class="clear" />
<div class="container">
	<?php if(isset($this->pageTitle)):?>
		<div class="sixteen columns pageTitle">
			<h2><?php echo $this->pageTitle;?></h2>
		</div>
	<?php endif;?>
</div>
<div id="pageContent" class="container">
	<?php echo $this->layout()->content; ?>
</div>
<?php echo $this->partial('foot.phtml');?>		
		


